version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    commit-message:
      prefix: "chore(deps): "
    open-pull-requests-limit: 10
