DirectoryPath: public
CheckDoctype: true
IgnoreAltMissing: false
IgnoreDirectoryMissingTrailingSlash: true
IgnoreDirs: [_print]
IgnoreEmptyHref: false
IgnoreInternalEmptyHash: true
IgnoreURLs:

TestFilesConcurrently: false
